### ISSUE TITLE
WA Web Update: isAuthenticated and ChatStore modules not found during initialization

### ISSUE THREAD

**Issue by soarxnetwork** [wppconnect-team/wa-js#3419]
Hey guys, looks like the latest WhatsApp Web update completely broke several core module finders in wa-js. 

I'm getting errors where it fails to find multiple modules during initialization. Specifically:
isAuthenticated is failing to resolve (seems like the .Z property with isRegistered/getLoginTokens has been renamed or changed).
ChatStore is not found (looks like ChatCollection is missing or renamed in the new chunk).
getIsMyContact, getMentionName, getPnForLid and a few other contact/profile related finders are also throwing "not found" errors.

Because of this, wppconnect.js is also throwing an uncaught TypeError: Cannot read properties of undefined (reading 'on'), probably because it's trying to attach an event listener to ChatStore which is currently undefined.

Just wanted to report this so the team is aware of the new Webpack changes from WhatsApp. Let me know if you need any console logs or diagnostic outputs!

**Comment by manfe** [comment]
@soarxnetwork can you try to get the `getBuildConstants` to know what is the version of it?

**Comment by soarxnetwork** [comment]
can you guide me how to getBuildConstants , i tried but i am not able to get @manfe

**Comment by soarxnetwork** [comment]
i figured it out now @manfe 

<img width="557" height="326" alt="Image" src="https://github.com/user-attachments/assets/07a1822d-8e84-4616-ad92-04e64add4237" />

if anyone else saw this and knows how to solve the above issue which i have raised, pls help me

**Comment by soarxnetwork** [comment]
<img width="575" height="618" alt="Image" src="https://github.com/user-attachments/assets/0c214c00-5c91-4d40-874f-ca3544e40137" />

<img width="570" height="650" alt="Image" src="https://github.com/user-attachments/assets/ff20a340-09d9-4c9f-9270-1b24e88e3f81" />

<img width="572" height="642" alt="Image" src="https://github.com/user-attachments/assets/06bada81-ed70-4173-8083-27edd46b03d3" />

<img width="576" height="684" alt="Image" src="https://github.com/user-attachments/assets/63f8fcdc-809a-40da-ab76-bbe54598e5d1" />

<img width="1366" height="682" alt="Image" src="https://github.com/user-attachments/assets/6bb22874-d087-4cc5-b2a8-323bef008021" />

<img width="1366" height="694" alt="Image" src="https://github.com/user-attachments/assets/a0c3d31c-2ff1-4673-a4cf-ef8eaffc5455" />

<img width="1366" height="718" alt="Image" src="https://github.com/user-attachments/assets/de9e7f04-5efd-4e39-9229-87a59f0e0f89" />

adding some more logs and images for context @manfe pls help

**Comment by manfe** [comment]
> can you guide me how to getBuildConstants , i tried but i am not able to get [@manfe](https://github.com/manfe)

on browser console:

`WPP.conn.getBuildConstants()`

it will return something like:

```
{
    "VERSION_PRIMARY": "2",
    "VERSION_SECONDARY": "3000",
    "VERSION_TERTIARY": "1039812514",
    "VERSION_BASE": "2.3000.1039812514",
    "WINDOWS_BUILD": null,
    "WINDOWS_OFFLINE": false,
    "VERSION_BASE_WITH_WINDOWS_BUILD": "2.3000.1039812514",
    "PUSH_PHASE": "C3",
    "VERSION_STR": "2.3000.1039812514",
    "DYN_ORIGIN": "https://web.whatsapp.com/",
    "WEB_PUBLIC_PATH": "/",
    "BUILD_URL": "https://web.whatsapp.com/",
    "PARSED": {
        "PRIMARY": 2,
        "SECONDARY": 3000,
        "TERTIARY": 1039812514
    }
}
```

**Comment by manfe** [comment]
Also looks like you are injecting wa-js before document being load

**Comment by dev-robin-hood** [comment]
> Also looks like you are injecting wa-js before document being load

Does it make sense to detect this in the library, since we could inject it at any time? @manfe

**Comment by nick8440** [comment]
Confirming on **wa-js 4.3.0 / WA Web 2.3000.1040316331**, injected at `document_idle` with `isFullReady === true` — so not an inject-before-load timing issue.

It's isolated to a **single module finder: `ChatStore` (`ChatCollection`)**. `ContactStore`, `MsgStore` and `conn` all bind fine — only `ChatStore` is `undefined` (see screenshot):

```js
typeof WPP.whatsapp.ChatStore             // "undefined"
await WPP.chat.list({ onlyUsers: true })  // TypeError: ...reading 'getModelsArray'
```

Looks like the same WA ≥ 2.3000.1039 webpack reshuffle you already handled for `createGroup` in #3460 — just the chat-collection finder this time, not a global init failure. Everything `ChatStore`-backed is down as a result (`chat.list`, `find`, `get`, `getActiveChat`). `WPP.conn.getBuildConstants()` → `VERSION_STR: "2.3000.1040316331"`. Happy to test a patch.


<img width="1775" height="601" alt="Image" src="https://github.com/user-attachments/assets/2265d316-3ed8-4a34-9889-0bfc69f07729" />

**Comment by soarxnetwork** [comment]
@manfe @nick8440 @dev-robin-hood @alantriesagain 

should i give you access to my github repo, can you check my code?
this would help me identify what mistake i am doing

**Comment by dev-robin-hood** [comment]
> [@manfe](https://github.com/manfe) [@nick8440](https://github.com/nick8440) [@dev-robin-hood](https://github.com/dev-robin-hood) [@alantriesagain](https://github.com/alantriesagain)
> 
> should i give you access to my github repo, can you check my code? this would help me identify what mistake i am doing

If your privacy concerns are okay with that, I can take a look.

**Comment by soarxnetwork** [comment]
<img width="1851" height="977" alt="Image" src="https://github.com/user-attachments/assets/c5e58c98-4314-4c16-9a28-6b137f821b90" />

added you as collaborator @dev-robin-hood

**Comment by dev-robin-hood** [comment]
Working without any problems...

`yarn install && yarn build`

@soarxnetwork

<img width="480" height="219" alt="Image" src="https://github.com/user-attachments/assets/e9d0b0f1-a89c-4de5-95e2-07a866ee7f55" />

**Comment by soarxnetwork** [comment]
@dev-robin-hood i used npm run build is there any diffrence

also 2 days ago dependabot suggested to bump wa-js version so i merged that pull request

did that solved the problem so it didnt came to you

Merge pull request https://github.com/soarxnetwork/wa-sender/pull/9 from soarxnetwork/dependabot/npm_and_yarn/wppconnect/wa-js-4.3.0
build(deps): bump @wppconnect/wa-js from 4.1.0 to 4.3.0

**Comment by soarxnetwork** [comment]
yesterday i was on my mac the extension was working perfectly but today i am on mint linux and wpp is not getting ready when i reload whatsapp web

<img width="616" height="985" alt="Image" src="https://github.com/user-attachments/assets/b197d248-cf56-46f0-b4c9-de81c194eb82" />

**Comment by dev-robin-hood** [comment]
To be honest, I don't believe it's a bug in wa-js, otherwise we'd have several open pull requests. I believe it's a bug in your library implementation.

The error logs you sent don't say anything; the error is cut off in your photo, it's the first error that appears. The test I did was using Debian, so this also has nothing to do with the operating system.

I would test it more for you, but unfortunately I don't have time.

I recommend closing the issue.

**Comment by gustavofariaas** [comment]
Hey guys, let me also share the same situation that happened to one of my users. I have this chrome extension that injects the wa-js, we have been receiving for a few times errors related to the same reported here, let me also shared my screenshots and buildConstants:

<img width="542" height="299" alt="Image" src="https://github.com/user-attachments/assets/9064d11d-970f-45a7-b0d8-6b43cfeaa48b" />

<img width="550" height="400" alt="Image" src="https://github.com/user-attachments/assets/a7336483-9bcd-4f17-b5ec-50e533a4386f" />

To replicate the issue, the user just opened the chrome browser and loaded the whatsapp, the extension app didnt work due to these errors above.

I'm currentley using WA-JS v4.3.0.

**Comment by gustavofariaas** [comment]
Hey! Let me also share what was the response from claude after reviewing the extension and the wa-source for the specific Whatsapp Web version:

Title: Module isAuthenticated / ChatStore not found on first page load (regression from loader refactor)

---
Description:

On the first page load with WhatsApp Web >= 2.3000.1041049695, users see:

Module isAuthenticated was not found with function(e){...e.isLoggedIn}
Module ChatStore was not found with function(e){return e.ChatCollection}
Uncaught TypeError: Cannot read properties of undefined (reading 'on')
Uncaught (in promise) TypeError: u.isAuthenticated is not a function

Reloading the page fixes

---
Root cause

Two independent issues:

1. Timing regression from commit be31b9f997

The old loader had a 1-second buffer after waitMainInit that implicitly ensured
all async WA bundles werean. The refactor replacedit with a waitUntil that only waits for WAWebUserPrefsMeUser — which resolves
before other bundles finis too early and findsnothing, it permanently caches null and never retries, even after the missing
bundles register.

On reload the browser serstantly, so there's no race condition.

2. Dead condition in isAuthenticated finder

The string getLoginTokens was removed from WA source and no longer exists in any
bundle. The first conditi:

m.Z?.toString().includes(
m.Z?.toString().includes('getLoginTokens') // ← always false, getLoginTokens is
gone

---
Suggested fixes

1. Restore a short delay after waitMainInit, or invalidate searchIdCache null
entries when new modules
2. Use module ID as primary matcher (existing pattern from NewsletterStore) and
drop the dead getLoginTok

// isAuthenticated.ts
(m, id) => id === 'WAWebUserPrefsIsLoggedIn' || m.isLoggedIn

// stores.ts / ChatCollection.ts
(m, id) => id === 'WAWebCction

---
Environment
- WA-JS: v4.3.0
- WhatsApp Web: 2.3000.1041049695
- Loader: Meta loader (>=

Hey @manfe ! hope you're doing good! does this analysis make sense to you? let me know if you need any additional info from my end.

**Comment by soarxnetwork** [comment]
@dev-robin-hood this issue only comes when i do hard refrresh on whatsapp web, on simply opening whatsapp web, it works perfectly fine

attaching a build of my extension, you can try running it simply once , and try hard refresh and then try to use, it will not work after hard refresh

code u already have for my repo, i respect your busy schedule but please help

[dist.zip](https://github.com/user-attachments/files/28740928/dist.zip)

<img width="1365" height="728" alt="Image" src="https://github.com/user-attachments/assets/4e9d6772-c08f-4078-a10f-a8c43a91dd13" />

**Comment by dev-robin-hood** [comment]
When you say wa-source, are you referring to the extension?

I should have put copyright lmao @gustavofariaas

**Comment by gustavofariaas** [comment]
@dev-robin-hood hey bud, wa-source I mean the dist build from wa-js project pointing to the version of my whatsapp web

**Comment by dev-robin-hood** [comment]
> [@dev-robin-hood](https://github.com/dev-robin-hood) hey bud, wa-source I mean the dist build from wa-js project pointing to the version of my whatsapp web

<img width="168" height="300" alt="Image" src="https://github.com/user-attachments/assets/cbc6f6df-fc85-4bfa-b73c-b062e76a3e3f" />

**Comment by gustavofariaas** [comment]
@dev-robin-hood HAHAHAHA 😂😂😂 im serious, i have cloned the project wa-js and downloaded the version of my whatsapp web, after built it generated a wa-source folder, this was the instance i used to inject the wa-js

**Comment by soarxnetwork** [comment]
@dev-robin-hood can you please check my last comment

**Comment by namansh70747** [comment]
@/private/tmp/claude-501/-Users-namansharma-mcp-servers/8c59b252-b891-4e88-b3ce-ef1e73d0a206/scratchpad/issue_comment.md
